name: tests
on:
  schedule:
    - cron: "* * * * *"

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: seet up
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies # Pythonの依存環境のインストール
        run: python -m pip install --upgrade pip
